business_name: My Awesome Business
business_information:
  - "Registration number: 1234567890"
functional_currency: GBP
accounts:
  -
    name: Cash
    type: Asset
  -
    name: Accounts receivable
    type: Asset
  -
    name: Office supplies
    type: Asset
  -
    name: Prepaid rent
    type: Asset
  -
    name: Equipment
    type: Asset
  -
    name: Common stock
    type: Equity
  -
    name: Accounts payable
    type: Liability
  -
    name: Notes payable
    type: Liability
  -
    name: Utilities payable
    type: Liability
  -
    name: Advance revenue
    type: Liability
  -
    name: Service revenue
    type: Income
  -
    name: Dividends
    type: Expense
  -
    name: Wages
    type: Expense
  -
    name: Miscellaneous expense
    type: Expense
  -
    name: Electricity bills
    type: Expense
  -
    name: Telephone bills
    type: Expense
currencies:
  -
    name: Pound Sterling
    code: GBP
    symbol: £
