business_name: Business Name
business_information:
  - "Business information"
base_url: "https://example.com/accounts"
functional_currency: ABC
accounts:
  -
    name: Debit example
    type: Asset
  -
    name: Credit example
    type: Liability
currencies:
  -
    name: Example Currency
    code: ABC
    symbol: A
